In [65]:
import numpy as np

In [66]:
rewards = np.arange(0, 1, 0.05, dtype=np.float64)

In [67]:
G = len(rewards)

In [68]:
mean = np.mean(rewards)
std = np.std(rewards)

In [69]:
advantages = (rewards - mean)/std

In [70]:
r_theta = np.random.rand(20) + 1

In [71]:
advantages, r_theta

(array([-1.64750894, -1.47408695, -1.30066495, -1.12724296, -0.95382097,
        -0.78039897, -0.60697698, -0.43355498, -0.26013299, -0.086711  ,
         0.086711  ,  0.26013299,  0.43355498,  0.60697698,  0.78039897,
         0.95382097,  1.12724296,  1.30066495,  1.47408695,  1.64750894]),
 array([1.68327021, 1.82764652, 1.78801827, 1.43424066, 1.60335564,
        1.41275434, 1.25299148, 1.57982039, 1.58412642, 1.65446998,
        1.85782526, 1.61644628, 1.61613166, 1.01104145, 1.38884564,
        1.84758455, 1.06924257, 1.03605379, 1.80073753, 1.96303148]))

In [72]:
EPS = 0.1

t1 = r_theta * advantages
t2 = np.clip(r_theta, 1 - EPS, 1 + EPS) * advantages

In [73]:
L_clipped = np.min([t1, t2], axis=0)

In [74]:
t1, t2

(array([-2.77320272, -2.69410988, -2.3256127 , -1.61673769, -1.52931423,
        -1.10251204, -0.76053698, -0.68493901, -0.41208354, -0.14346074,
         0.16109388,  0.42049101,  0.70068194,  0.61367888,  1.08385371,
         1.76226489,  1.20529616,  1.34755886,  2.65444369,  3.23411192]),
 array([-1.81225984, -1.62149564, -1.43073145, -1.23996726, -1.04920306,
        -0.85843887, -0.66767468, -0.47691048, -0.28614629, -0.0953821 ,
         0.0953821 ,  0.28614629,  0.47691048,  0.61367888,  0.85843887,
         1.04920306,  1.20529616,  1.34755886,  1.62149564,  1.81225984]))

In [77]:
L_clipped

array([-2.77320272, -2.69410988, -2.3256127 , -1.61673769, -1.52931423,
       -1.10251204, -0.76053698, -0.68493901, -0.41208354, -0.14346074,
        0.0953821 ,  0.28614629,  0.47691048,  0.61367888,  0.85843887,
        1.04920306,  1.20529616,  1.34755886,  1.62149564,  1.81225984])